name: Rails Tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Install SQLite
      run: |
        sudo apt-get install libsqlite3-dev

    - name: Install dependencies
      env:
        RAILS_ENV: test
      run: |
        sudo apt-get -y install libpq-dev
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Setup test database
      env:
        RAILS_ENV: test
      run: make setup

    - name: Run Tests
      run: make test

    - name: Run lint
      run: make lint
